Repository ProjektyUstaw/Ustawy-o-PIT, pull requests merged in 2023-06, with the labels that each got.

#130 Ujednolicenie numeracji, wciec, pozbycie sie auto orderingu, dodanie lintowania skladni Markdown
  .github/workflows/md-lint.yml
  .markdownlint.yaml
  README.md
  wersje tekstowe/PIT dla inwestorów - ustawa.md
  wersje tekstowe/PIT dla przedsiębiorców - ustawa.md
  wersje tekstowe/PIT dla zatrudnionych - ustawa.md
  wersje tekstowe/Podstawowe założenia projektu.md
Labels: techniczne

#194 Kwota ulgi dla seniorów i młodych, ulga na dziecko
  wersje tekstowe/PIT dla zatrudnionych - ustawa.md
Labels: PIT dla zatrudnionych

#159 Drobne poprawki
  wersje tekstowe/Podstawowe założenia projektu.md
Labels: ulepszenie

#270 „Założenia”: poprawki markdown
  Podstawowe założenia projektu.md
Labels: techniczne
